title: Sviluppo Web Avanzato
description: Sviluppo Web Avanzato course pages, University of L'Aquila
course: Sviluppo Web Avanzato
plugins:
  - jekyll-relative-links
  - jekyll-redirect-from 
whitelist:
  - jekyll-redirect-from
relative_links:
  enabled: true
  collections: true
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"